[package]
name = "countdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schedule_recv = "0.1.0"
clearscreen = "2.0.1"
rand = "0.8.4"